---
title: "Anàlisi Descriptiva Univariant Preprocessat"
output:
  pdf_document: default
  html_document:
    df_print: paged
  word_document: default
date: "2023-09-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment=NA, warning = FALSE, message = FALSE)

setwd("C:/Users/Usuario/Documents/Universitat/4rt Quatri/PMAAD_git/PMAAD_GIA")
load("./3_Preprocessing/data_knn_imputed_unknown.RData")
dataset <- na.omit(data)
dataset[,"lyrics"] <- NULL
library(ggplot2)
library(dplyr)
library(viridis)
library(summarytools)

spotyPalette <- c("#1db954","#ff7b24", "#c6182c", "#df75ff", "#eea990", "#98EEB7", "#e1ece3", "#cdf564", "#1ed760", "#4b917d","#2d6d62",
                           "#457e59", "#535353", "#3e3d54" , "#212121", "#121212")

```

# Anàlisi Descriptiva Univariant Preprocessat

Les dimensions del nostre dataset són:
```{r, echo=FALSE}
k = dim(dataset)
cat('N = ',k[1], '\n')
cat('K = ',k[2], '\n')

```

Per tal de poder observar les variables, procedirem a fer els bar plots, pie charts (categòriques) i els histogrames i boxplots (per les numèriques).

----------------------------------------------------------------------
```{r, echo=FALSE}
dataset[,"major_mode"] <- as.factor(dataset[,"major_mode"])
dataset[,"key"] <- as.factor(dataset[,"key"])
dataset[,"month_week"] <- as.factor(dataset[,"month_week"])
dataset[,"year_week"] <- as.factor(dataset[,"year_week"])
dataset[,"month_release"] <- as.factor(dataset[,"month_release"])
dataset[,"time_signature"] <- as.factor(dataset[,"time_signature"])

univariate_numeric <- function(X, nom){
  hist_plot <- ggplot(data = dataset, aes(x = X)) +
      geom_histogram(bins = 15, fill = "#1db954", color = "#FFFFFF") +
      labs(title = paste("Histograma de ", nom), x = "Value", y = "Frequency") 
    
    box_plot <- ggplot(data = dataset, aes(y = X)) +
      geom_boxplot(fill = "#1db954", color = "black") +
      labs(title = paste("Boxplot de ", nom), x = "", y = "Value") +
      theme_minimal()
    
    print(hist_plot)
    print(box_plot)
    
    summary_stats <- summary(X)
    cat('Mínim: ', summary_stats[1], '     ')
    cat('Màxim: ', summary_stats[6], '\n\n')
    cat('Primer quartil: ', summary_stats[2], '     ')
    cat('Mediana: ', summary_stats[3], '     ')
    cat('Tercer quartil: ', summary_stats[5], '     ')
    cat('Mitjana: ', summary_stats[4], '\n\n')
    cat(paste("Desviació estàndar: ", sd(X, na.rm = TRUE), "     "))
    cat(paste("Variància: ", sd(X, na.rm = TRUE) / mean(X, na.rm = TRUE), "\n\n"))
    cat("\n\n")
}

univariate_date <- function(X,nom){
  hist_plot <- ggplot(data = dataset, aes(x = X)) +
    geom_histogram(binwidth = 1, fill = "#1db954", color = "black", show.legend = FALSE) +
    labs(title = paste("Histograma de ", nom), x = "Value", y = "Frequency") +
    theme_minimal()
  box_plot <- ggplot(data = dataset, aes(x = "", y = X)) +
    geom_boxplot(fill = "#1db954", color = "black", show.legend = FALSE) +      labs(title = paste("Boxplot de ", nom), x = "", y = "Value") +
    theme_minimal()
    
  print(hist_plot)
  print(box_plot)
  cat("\n\n")
}

univariate_cat <- function(X, nom){
  binary_color_mapping <- c("TRUE" = "#1db954", "FALSE" = "#ff7b24", "0" = "#1db954", "1" = "#ff7b24", "True" = "#1db954" , "False" = "#ff7b24" )
  category_counts <- table(X)
    category_df <- as.data.frame(category_counts)
    
    colnames(category_df) <- c("Categoria", "Freqüència")
    
    sub_category_df <- category_df
    
    order_indices <- order(sub_category_df$Freqüència, decreasing = TRUE)
    sub_category_df <- sub_category_df[order_indices, ]
    
    sub_category_df$Categoria <- factor(sub_category_df$Categoria, levels = sub_category_df$Categoria[order(sub_category_df$Freqüència, decreasing = TRUE)])
      
sub_category_df$Freqüència
    
    if(nrow(sub_category_df) > 15){
      sub_category_df <- sub_category_df[1:15,]}
    # Bar plot
    if (length(unique(X)) == 2){
      bar_plot <- ggplot(data = sub_category_df, aes(x = Categoria, y = Freqüència, fill = Categoria)) +
      scale_fill_manual(values = binary_color_mapping, name = "Category") +
      geom_col(show.legend = FALSE) +
      labs(title = paste("Distribució de categories de ", nom),
           x = "Category",
           y = "Frequency") +
      theme_minimal() +
       geom_text(aes(label = Freqüència), position = position_dodge(width = 1), vjust = -0.5) +
       theme(axis.text.x = element_text(angle = 45, hjust = 1))
      
    
    # Pie chart
    sub_category_df[,"Percentatge"] <- (sub_category_df[,"Freqüència"] / sum(sub_category_df[,"Freqüència"])) * 100
    
      pie_chart <- ggplot(data = sub_category_df, aes(x = "", y = Freqüència, fill = Categoria)) +
      geom_bar(stat = "identity") +
      coord_polar(theta = "y") +
      labs(title = paste("Pie Chart de ", nom)) +
      theme_void() +
      geom_text(aes(label = paste0(round(Percentatge, 1), "%")), position = position_stack(vjust = 0.5)) +
      scale_fill_manual(values = binary_color_mapping, name = "Category") +
  guides(fill = guide_legend(title = "Category"))
    }
    else{
      bar_plot <- ggplot(data = sub_category_df, aes(x = Categoria, y = Freqüència, fill = Categoria)) +
      scale_fill_manual(values = spotyPalette) +
      geom_col(show.legend = FALSE) +
      labs(title = paste("Distribució de categories de ", nom),
           x = "Category",
           y = "Frequency") +
      theme_minimal() +
       geom_text(aes(label = Freqüència), position = position_dodge(width = 1), vjust = -0.5) +
       theme(axis.text.x = element_text(angle = 45, hjust = 1))
      
    
    # Pie chart
    sub_category_df[,"Percentatge"] <- (sub_category_df[,"Freqüència"] / sum(sub_category_df[,"Freqüència"])) * 100
    
      pie_chart <- ggplot(data = sub_category_df, aes(x = "", y = Freqüència, fill = Categoria)) +
      geom_bar(stat = "identity") +
      coord_polar(theta = "y") +
      labs(title = paste("Pie Chart de ", nom)) +
      theme_void() +
      geom_text(aes(label = paste0(round(Percentatge, 1), "%")), position = position_stack(vjust = 0.5)) +
      scale_fill_manual(values = spotyPalette, name = "Category") +
  guides(fill = guide_legend(title = "Category"))
    }
    
    print(bar_plot)
    print(pie_chart)
    
    cat(paste("Nombre de modalitats: ", length(category_df[,"Freqüència"]), '\n\n'))
    cat(paste("Moda: ", sub_category_df[,"Categoria"][1], "\n\n"))
    cat(paste("Freqüència màxima: ", sub_category_df[,"Freqüència"][1], "\n\n"))
    cat("\n\n")
}

```


```{r, echo=FALSE,out.width="50%",  results='asis'}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
univariate <- function(X, nom) {
  cat('##', nom, "\n\n")
  print(head(X))
  if (is.numeric(X)) {
    univariate_numeric(X,nom);
  } else if (class(X) == "Date") {
    univariate_date(X,nom);
  } else {
    # Bar plot and Pie chart for categorical data
    univariate_cat(X,nom);
  }
}

# Iterate through columns and create univariate plots
c = -1
for (i in c(2:k[2])) {
  univariate(dataset[, i], names(dataset)[i])
  c = c + 1
  if (c==2){
    c = 0
    cat("\n \n \\newpage \n")
    cat("\n")
  }
}
```

